name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [8.0]
    steps:
      - uses: actions/checkout@v4

      - name: Hello World Demo
        run: echo "👋 Hello, GitHub Actions!"

      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore src/HelloWorld/HelloWorld.csproj

      - name: Build
        run: dotnet build src/HelloWorld/HelloWorld.csproj --configuration Release --no-restore

      - name: Test(vstest)
        run: |
          dotnet build tests/HelloWorld.Tests/HelloWorld.Tests.csproj \
            --configuration Release

          dotnet vstest "tests/HelloWorld.Tests/bin/Release/net8.0/HelloWorld.Tests.dll" \
            --Logger:trx

