name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [7.0, 8.0]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore src/HelloWorld/HelloWorld.csproj

      - name: Build
        run: dotnet build src/HelloWorld/HelloWorld.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/HelloWorld.Tests/HelloWorld.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

